package si.uni_lj.fri.xml2owl.rules.service;

import javax.xml.ws.WebFault;
import si.uni_lj.fri.xml2owl.rules.service.types.RulesFault;

/** The exception thrown when a problem arises during XML2OWL ruleset
 * validation. */
@WebFault(faultBean="si.uni_lj.fri.xml2owl.rules.service.types.RulesFault",
          targetNamespace="http://www.fri.uni-lj.si/xml2owl/rules", 
          name="rulesFault")
public class Xml2OwlRulesException
  extends Exception
{
    private RulesFault faultInfo;

    public Xml2OwlRulesException(String message) {
	super(message);
    }

    public Xml2OwlRulesException(String message, RulesFault faultInfo)
    {
	super(message);
	this.faultInfo = faultInfo;
    }

    public Xml2OwlRulesException(String message, 
                                 RulesFault faultInfo, 
                                 Throwable t)
    {
	super(message,t);
	this.faultInfo = faultInfo;
    }

    public RulesFault getFaultInfo()
    {
	return faultInfo;
    }

    public void setFaultInfo(RulesFault faultInfo)
    {
	this.faultInfo = faultInfo;
    }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)
