package si.uni_lj.fri.xml2owl.map.service;

import javax.xml.ws.WebFault;

/** The exception thrown when a problem arises during XML2OWL mapping. */
@WebFault(faultBean="si.uni_lj.fri.xml2owl.map.service.types.MapFault",
  targetNamespace="http://www.fri.uni-lj.si/xml2owl", name="mapFault")
public class Xml2OwlMapException
  extends Exception
{
  private si.uni_lj.fri.xml2owl.map.service.types.MapFault faultInfo;

    public Xml2OwlMapException(String message) 
  {
    super(message);
  }


  public Xml2OwlMapException(String message,
                             si.uni_lj.fri.xml2owl.map.service.types.MapFault faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public Xml2OwlMapException(String message,
                             si.uni_lj.fri.xml2owl.map.service.types.MapFault faultInfo,
                             Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public si.uni_lj.fri.xml2owl.map.service.types.MapFault getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(si.uni_lj.fri.xml2owl.map.service.types.MapFault faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)
